spring.application.name=project-t

spring.datasource.url=jdbc:postgresql://localhost:5432/betting
spring.datasource.username=changeUsername
spring.datasource.password=changePassword

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.file.name=project-t